sonar.projectKey=AzTTeK_MiniMarket24
sonar.organization=azttek-1

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=MiniMarket24
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file.
sonar.sources=logica_negocio,modulo_analitico
sonar.tests=logica_negocio/tests,modulo_analitico/tests

# Encoding of the source code.
sonar.sourceEncoding=UTF-8

# Coverage report path
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/tests/**, **/__init__.py, data/**, notebooks/**, visualizacion/**
