sonar.projectKey=AzTTeK_MiniMarket24
sonar.organization=azttek-1

# Metadata
sonar.projectName=MiniMarket24
sonar.projectVersion=1.0

# Scope of Analysis
sonar.sources=logica_negocio,modulo_analitico
sonar.tests=logica_negocio/tests,modulo_analitico/tests

# Explicit Inclusions (to avoid noise from other files)
sonar.inclusions=logica_negocio/**/*.py,modulo_analitico/**/*.py
sonar.test.inclusions=logica_negocio/tests/**/*.py,modulo_analitico/tests/**/*.py

# Python Configuration
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8

# Coverage Report Path
sonar.python.coverage.reportPaths=coverage.xml

# Exclusions to clean up the report
sonar.exclusions=**/tests/**, **/__init__.py, data/**, notebooks/**, visualizacion/**, Documents/**, *.py
